name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main 
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "images/diagram.svg"
          excluded_paths: "ignore,.github,notes,images"
          excluded_globs: "**/*.{png,ico,md};/*.*"
          branch: diagram
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update diagram
          title: Update diagram
          body: |
            This PR updates the diagram.
          labels: diagram
          branch: main 
          base: diagram
           