name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main 
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "images/diagram.svg"
          excluded_paths: "ignore,.github,notes,images"
          excluded_globs: "**/*.{png,ico,md};/*.*"
          branch: diagram
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update diagram
          title: Update diagram
          body: |
            Update repo-visualization diagram
      # delete branch after PR is merged
      - name: Delete branch
        uses: peter-evans/delete-branch@v1
        with:
          branch: diagram
          